
# 1. Member 단일 조회
GET {{host}}/api/members/1
Content-Type: application/json

###

# 2. Member 생성
POST {{host}}/api/members
Content-Type: application/json

{
  "email": "mmm@gmail.com",
  "name": "mmm"
}


###
# 3. Member 수정
PUT {{host}}/api/members/1
Content-Type: application/json

{
  "name": "abc"
}

###
# 4. Member 페이지 조회
GET {{host}}/api/members?page=0&size=1
Content-Type: application/json